### ISSUE TITLE
Details on Experiment settings in Table 1.

### ISSUE THREAD

**Issue by zhou13** [JiahuiLei/MoSca#9]
Thank you for sharing the excellent project! My question is regarding Table 1 of the paper. It seems that the performance of baseline approaches, e.g., Shape-of-Motion, does not match the metrics reported in the original paper.

For example, the mPSNR and mSSIM of Shape-of-motion reported in MoSca is 17.32, 0.598, while they are 16.72, 0.63 report in the shape-of-motion. What is the reason for this discrepancy? Is it because you used a different mask?

In addition, according to table 6, the usage of LIDAR depth on the DyCheck results in more than 2 points of performance improvement compared to predicted depth. Did you use the LIDAR depth or predicted depth from some monodepth networks when running the baselines in Table 1? I wonder how does that affect the performance of baselines.

**Comment by JiahuiLei** [comment]
Thanks for your questions,

1. We report Shape-of-Motion in two rows in Tab.1, you can see the exact same number in group SOM-5-1x at the bottom because Shape-of-Motion uses only 5 scenes while all other baselines use all 7 scenes for evaluation. Additionally, all other baselines use 2x downsampled resolution but SOM uses 1x resolution. For a fare comparison, we do two sides (A) we run SOM on the standard 7 scenes 2x benchmark and get the performance 17.32, 0.598 (B) and we also run our method on the same 5 scene 1x resolution with SOM to report the bottom SOM-5-1x group.

2. Lidar depth is noisy and incomplete, but metric-wise (exact scale) it is much more accurate than any monocular depth model. Because DyCheck is a realistic, challenging dataset with test views far away from the training, the depth metric-wise accuracy plays an important role in getting good metrics like PSNR.  In Tab.1 All the baselines are reported from their original paper and almost all of them use the LiDAR depth. Some baselines, for example, Shape-of-Motion, even align dep-anything onto the Lidar depth, which also exploits the metric-accurate lidar information. Usually, if a paper compares on Dycheck but doesn't use lidar, they will explicitly list this and highlight the two tables with or without lidar, because by default Dycheck baselines are all using lidar.


Hope the above info can help

**Comment by zhou13** [comment]
The information is really helpful. Thank you so much.

**Comment by FantasticOven2** [comment]
> Some baselines, for example, Shape-of-Motion, even align dep-anything onto the Lidar depth

Hey @zhou13 @JiahuiLei ! Regarding the depth setup for DyCheck in Shape-of-Motion, we re-run colmap on five scenes and aligned mono-depth from Depth-Anything with the colmap point cloud. We didn't use the lidar depths/cameras
